### ISSUE TITLE
Old AngularJs version

### ISSUE THREAD

**Issue by goliney** [FineUploader/integration-examples#1]
Angularjs version being used in example code is `1.0.7`. Can you upgrade an example to higher version (`1.3.x`)?

**Comment by rnicholus** [comment]
Yep, that shouldn't be a problem.  I've been using 1.3.x on other projects myself lately, so it should be a simple task.  If there are other improvements/additions you'd like to see in that example or others, please let me know.

**Comment by rnicholus** [comment]
@feltnerm You may be in a position to update this quickly, given your current assignment.

**Comment by rnicholus** [comment]
I'd like to update the example to use Angular 1.3.x and remove the dependence on jQuery. I hope to work on this after 5.2 is released, but possibly not until after 5.3.

TODO:
- [x] Remove jQuery dependence 
- [x] Upgrade to Angular 1.3.x
- [x] Remove dependence on bootstrap. 
- [ ] Consider moving example to a dedicated public repo.
- [x] Clean up the example. This was one of my earlier experiences with angular and I can see a number of prudent adjustments to make.
- [x] Pull fine uploader and all other dependencies from NPM

**Comment by zeroasterisk** [comment]
:+1: I'd love to see this example improved and updated too...  

I can't even get it to load, with fineuploader v5.4.1

![ss](http://puu.sh/lFGhs/6c237b5bd9.png)
![ss](http://puu.sh/lFGou/2ea8e30212.png)

**Comment by rnicholus** [comment]
Yes, this is a bit old. I can see updating it to the latest Angular 1.x version, but I doubt this will ever be updated to Angular 2.x (at least, not by me). There's a lot of other work scheduled for Fine Uploader 5.5 and 6.0 at the moment, and we have a limited number of hours and people to complete these tasks, so, I'm not sure exactly when this will happen. 

My suggested approach for restructuring this example involves:
- a simple Fine Uploader directive with no external dependencies (other than Angular)
- a service that exposes the Fine Uploader instance for use by other directives, controllers, and services

This shouldn't be tough to complete.

**Comment by rnicholus** [comment]
I realize how important this example may be for AngularJS users, so I'm going to prioritize updating this for Angular 1.5 and Fine Uploader 5.4+. I hope to begin on this within the next week, and intend to update the GitHub code and associated blog post.

**Comment by rnicholus** [comment]
Code is completed and being staged in the update-angular-example branch. Last step before merging into master is to update the article at http://blog.fineuploader.com/2013/11/01/full-stack-javascript-image-uploader-using-angularjs-node-js/.

**Comment by goliney** [comment]
@rnicholus Great news! Thanks

**Comment by rnicholus** [comment]
GitHub repo and blog post have been updated!
