### ISSUE TITLE
Demo s3 Uploader wont upload files larger than 5 meg in ie8

### ISSUE THREAD

**Issue by joebtron** [FineUploader/integration-examples#2]
Hi, I've noticed that the s3 uploader on the demo page http://fineuploader.com/demos.html doesn't work with files larger than 5 meg in ie8. Is this a problem that can be worked around or is it to do with chunked s3 upload and you can't have both?

**Comment by rnicholus** [comment]
What do you mean "doesn't work"? What exactly happens? There is a file size restriction in that specific demo for all browsers (15mb). This is enforced for older browsers via a policy document.

 Also this should be posted in the fine uploader issue tracker.

**Comment by rnicholus** [comment]
I just uploaded a 10 MB file in IE8 via the S3 demo without issue. If you are still seeing an issue, please open something in the fine uploader repo with a detailed description of the problem and exact steps required to reproduce.
